// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
import { z } from "npm:zod@^4";
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the LAPAU.ID product catalog by name, barcode, or tag. Returns id, name, selling price, current stock, category, and barcode.",
  inputSchema: {
    query: z.string().min(1).describe("Search text: product name, barcode, or tag."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const max = limit ?? 10;
    const { data, error } = await supabase.from("products").select("id, name, selling_price, current_stock, barcode, categories(name)").or(`name.ilike.%${query}%,barcode.ilike.%${query}%`).limit(max);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.0";
import { z as z2 } from "npm:zod@^4";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product details",
  description: "Fetch full details for a single product by id or barcode.",
  inputSchema: {
    id: z2.string().uuid().optional().describe("Product UUID."),
    barcode: z2.string().optional().describe("Product barcode.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, barcode }) => {
    if (!id && !barcode) {
      return { content: [{ type: "text", text: "Provide id or barcode." }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("products").select("*, categories(name), brands(name)").limit(1);
    q = id ? q.eq("id", id) : q.eq("barcode", barcode);
    const { data, error } = await q.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Product not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-low-stock.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.50.0";
import { z as z3 } from "npm:zod@^4";
var list_low_stock_default = defineTool3({
  name: "list_low_stock_products",
  title: "List low-stock products",
  description: "List products whose current_stock is at or below a threshold. Useful for restock planning.",
  inputSchema: {
    threshold: z3.number().int().min(0).max(1e3).optional().describe("Stock threshold (default 5)."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max results (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ threshold, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("products").select("id, name, current_stock, selling_price, barcode, categories(name)").lte("current_stock", threshold ?? 5).order("current_stock", { ascending: true }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/sales-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.50.0";
import { z as z4 } from "npm:zod@^4";
var sales_summary_default = defineTool4({
  name: "sales_summary",
  title: "Sales summary",
  description: "Summarize transactions between two dates: total revenue, transaction count, and count grouped by source (POS vs FRONTEND_ORDER).",
  inputSchema: {
    start_date: z4.string().describe("ISO date, e.g. 2026-07-01."),
    end_date: z4.string().describe("ISO date, inclusive end, e.g. 2026-07-06.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("transactions").select("id, total, source, created_at").gte("created_at", `${start_date}T00:00:00Z`).lte("created_at", `${end_date}T23:59:59Z`);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = data ?? [];
    const revenue = rows.reduce((acc, r) => acc + Number(r.total ?? 0), 0);
    const bySource = rows.reduce((acc, r) => {
      const key = r.source ?? "UNKNOWN";
      acc[key] ??= { count: 0, revenue: 0 };
      acc[key].count += 1;
      acc[key].revenue += Number(r.total ?? 0);
      return acc;
    }, {});
    const summary = { start_date, end_date, transaction_count: rows.length, total_revenue: revenue, by_source: bySource };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lapau-id-mcp",
  title: "LAPAU.ID MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the LAPAU.ID retail app: search the product catalog, look up product details, list low-stock products, and summarize sales over a date range.",
  tools: [search_products_default, get_product_default, list_low_stock_default, sales_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
