// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkqfdwxunnymmsutbeuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrcWZkd3h1bm55bW1zdXRiZXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1ODA5OTAsImV4cCI6MjA2NTE1Njk5MH0._bpDEJQ-7QjBtLrVTxpmriDIdAglQPJd2VdypgKw_9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);